#!/bin/sh

for L in $(find . -name "*.dll"); do echo $L | xargs git checkout; done;
for L in $(find . -name "*.exe"); do echo $L | xargs git checkout; done;
for L in $(find . -name "*.pdb"); do echo $L | xargs git checkout; done;
